a = int(input('Nhap a = '))
b = int(input('Nhap b ='))
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a // b =', a // b)
print('a ** b =', a ** b)
print('a % b =', a % b)
if a > b:
    print('a lon hon b')
elif a < b:
    print('a nho hon b')
else:
    print('a bang b')
print(a & b)
print(a | b)
print(a ^ b)
print(not a == b)
print(a << 1)
print(a >> 1)